[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm run build"
  
[functions.render]
  external_node_modules = ["chrome-aws-lambda"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
