[build.environment]
  NODE_VERSION = "18.12.0"

[build]
  publish = "dist"
  command = "pnpm run build"

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
