[build.environment]
  NODE_VERSION = "18.12.0"

[build]
  publish = "dist"
  command = "npx playwright install && pnpm run build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
